# Generated by Django 4.1.5 on 2023-01-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_alter_friend_group_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrecord',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
