# Generated by Django 4.1.5 on 2023-01-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
